name: Merge Category Lists

on:
  push:
    paths:
      - 'Categories/*.lst'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Merge .lst files
        run: |
          # Очистим или создадим файл
          > all-list.lst

          # Объединяем .lst-файлы в алфавитном порядке, гарантируя пустую строку между блоками
          for file in Categories/*.lst; do
            sed -e '$a\' "$file" >> all-list.lst  # добавляет перевод строки, если нет
            echo "" >> all-list.lst               # добавляем пустую строку между блоками
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add all-list.lst
          git diff --cached --quiet || git commit -m "Auto-merge category lists into all-list.lst"
          git push
